apiVersion: v1
kind: Namespace
metadata:
  name: finance

---

apiVersion: v1
kind: Namespace
metadata:
  name: hello

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: messaging
  labels:
    tier: msg
spec:
  containers:
  - name: redis-container
    image: redis:alpine

---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  selector:
    tier: msg
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-web-app
  template:
    metadata:
      labels:
        app: hr-web-app
    spec:
      containers:
        - name: httpd-container
          image: httpd:alpine

---

apiVersion: v1
kind: Pod
metadata:
  name: temp-bus
  namespace: finance
spec:
  containers:
    - name: redis-container
      image: redis:alpine

---

apiVersion: v1
kind: Service
metadata:
  name: hr-web-app-service
  namespace: default
spec:
  selector:
    app: hr-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
  type: NodePort

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: date-script
data:
  script.sh: |
    #!/bin/sh
    date -u +"%Y-%m-%dT%H:%M:%SZ"

---

apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["sh /scripts/script.sh && sleep 1000"]
    volumeMounts:
    - name: date-script-volume
      mountPath: /scripts
  volumes:
  - name: date-script-volume
    configMap:
      name: date-script

